version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  reviewers:
  - ethanwu10
  labels:
  - kind/dependencies
  ignore:
  - dependency-name: pre-commit
    versions:
    - 2.10.0
    - 2.11.0
    - 2.12.0
  - dependency-name: sphinx
    versions:
    - 3.4.3
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
  - dependency-name: flake8-bugbear
    versions:
    - 21.3.1
    - 21.3.2
  - dependency-name: docker
    versions:
    - 4.4.1
    - 4.4.2
    - 4.4.3
  - dependency-name: mypy
    versions:
    - "0.800"
